// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVO846gcXSprhi1ZDiXtVAB6cpAiMSZ20',
    appId: '1:855941237369:web:32eceb682a5cfe2d2fa2a8',
    messagingSenderId: '855941237369',
    projectId: 'todo2-9edb6',
    authDomain: 'todo2-9edb6.firebaseapp.com',
    storageBucket: 'todo2-9edb6.appspot.com',
    measurementId: 'G-P0NQRNB33K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgXlHxhzoE57BNA4TxaDNe_FJIFNQOiBQ',
    appId: '1:855941237369:android:f452f6b750686ec32fa2a8',
    messagingSenderId: '855941237369',
    projectId: 'todo2-9edb6',
    storageBucket: 'todo2-9edb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDNSlV5c61utfMZLBLUx3fpM3uyygUCj4',
    appId: '1:855941237369:ios:135407353eaaf5972fa2a8',
    messagingSenderId: '855941237369',
    projectId: 'todo2-9edb6',
    storageBucket: 'todo2-9edb6.appspot.com',
    iosBundleId: 'com.solo3.todo2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDNSlV5c61utfMZLBLUx3fpM3uyygUCj4',
    appId: '1:855941237369:ios:1e4f4e5b0b03c14f2fa2a8',
    messagingSenderId: '855941237369',
    projectId: 'todo2-9edb6',
    storageBucket: 'todo2-9edb6.appspot.com',
    iosBundleId: 'com.solo3.todo2.RunnerTests',
  );
}
